### ISSUE TITLE
Error on Group Edit Permissions - Drupal 8.6.4 

### ISSUE THREAD

**Issue by kclarkson** [Gizra/og#454] opened 2018-12-20 21:48 UTC
I have just installed OG alpha2 on simplytest.me. It is using 8.6.4 

When visiting admin/config/group/permissions/node/event I receive a white screen with the message `The website encountered an unexpected error. Please try again later.`

**Comment by zerolab** [comment] 2018-12-21 09:23
You likely need #243, not sure how that would work with simplytest.me
 It would also help if you could provide further errors (e.g. what is the associated PHP error in the database log?)

**Comment by MPParsley** [comment] 2019-05-11 11:29
This is a duplicate of #232, the ui forms to manage permissions aren't developed yet. As @zerolab mentioned, you'll need #243.

**Closed as completed by MPParsley** 2019-05-11 11:29 UTC
Labels: Bug, Drupal 8
