### ISSUE TITLE
Fix failing travis for D7

### ISSUE THREAD

**Issue by amitaibu** [Gizra/og#133] opened 2016-07-04 11:21 UTC
We can probably install higher PHP as-well

@nirgn975 this one has your name on it :)

**Comment by krueschi** [comment] 2016-09-21 15:29
When tinkering around with travis-ci testing I found that installing drush with composer (instead of pear) brings up no error message. So I changed

```
- pear channel-discover pear.drush.org
- pear install drush/drush-5.8.0
```

and put instead

```
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- composer global require drush/drush:6.*
```

BUT: I have not yet figured out how to install the drupal testing environment using the drush site-install command correctly, so my travis-ci tests fail.

Maybe it helps nonetheless.

Credits for this go to https://www.drupal.org/u/dsnopek at https://www.drupal.org/node/2195445.

**Comment by AronNovak** [comment] 2017-04-18 05:43
Now the Travis itself is fixed, the test execution is there, the issue is that the tests seem to be broken right now:
![test](https://cloud.githubusercontent.com/assets/114076/25116073/b49397d6-240a-11e7-885e-61e01d7372a0.png)

**Comment by AronNovak** [comment] 2017-04-18 05:44
Of course that"s something to validate against a local execution

**Comment by AronNovak** [comment] 2017-04-18 06:15
I have almost the same failures at localhost, so it"s not Travis specific that it fails:
![localfail](https://cloud.githubusercontent.com/assets/114076/25116780/224cdf0e-240f-11e7-9b46-91c3d25611c4.png)
@amitaibu should we proceed in the same PR by fixing the tests itself in addition to Travis?

**Comment by AronNovak** [comment] 2017-04-18 06:26
We need to restore the internal webserver and re-evaluate the above findings.
```
Pass      Browser    og_ui.test         309 OgUiManagePeopleTestCase->testOgUiD
    GET http://localhost/group/entity_test/1/admin/people/delete-membership/2
    returned 404 (250 bytes).
Pass      Browser    og_ui.test         309 OgUiManagePeopleTestCase->testOgUiD
    Valid HTML found on
    "http://localhost/group/entity_test/1/admin/people/delete-membership/2"
Fail      Other      og_ui.test         309 OgUiManagePeopleTestCase->testOgUiD
    Found the Remove button
```

**Comment by AronNovak** [comment] 2017-04-21 06:39
Almost all the tests pass, but:
```
The command "php scripts/run-tests.sh --url http://127.0.0.1:8080 --php $(phpenv which php) --concurrency 2 --verbose --color "Organic groups","Organic groups access","Organic groups context","Organic groups field access","Organic groups UI" 2>&1 | tee /tmp/simpletest-result.txt" exited with 0.

$ egrep -i "([1-9]+ fail)|(Fatal error)|([1-9]+ exception)" /tmp/simpletest-result.txt && exit 1

OG group membership approval 17 passes, 1 fail, 0 exceptions, and 4 debug messages

OG UI manage people 94 passes, 1 fail, 0 exceptions, and 28 debug messages
```
So the vast majority of the tests pass, indeed now it should be compared with localhost, if these failures come from the test/module itself.

**Comment by AronNovak** [comment] 2017-05-12 14:47
Indeed it's reproducible at local, the exact problematic lines:
```
 aaron  ~  gizra  drupal-7.x  cat /tmp/simpletest-result.txt  | grep Fail
Fail      Other      og_access.test     461 OgAccessModeratedGroupApproval->tes
Fail      Browser    og_ui.test         434 OgUiManagePeopleTestCase->testOgUiP
```

**Comment by AronNovak** [comment] 2017-05-12 14:58
The two failing assertions:
./og_access/og_access.test:
```
    // Save user as a member of the group, without passing state.
    $this->user->og_user_node[LANGUAGE_NONE][0]['target_id'] = $this->group->nid;
    user_save($this->user);

    // User's membership should be pending.
    $membership = og_get_membership('node', $this->group->nid, 'user', $this->user->uid);
    $this->assertEqual($membership->state, OG_STATE_PENDING, t('User membership is pending.'));
```

And:
og_ui/og_ui.test:
```
    // Numeric values that are not integers are forbidden, too.
    $this->drupalGet('entity_test/' . $this->entity->pid . '.333/group');
    $this->assertResponse(403);
```

**Comment by AronNovak** [comment] 2017-09-19 08:25
We achieved the green Travis for 7.x, we can close this issue (I don't have the permission for that).

**Closed as completed** 2017-09-19 09:02 UTC
