### ISSUE TITLE
UI for Permissions and Roles is missing

### ISSUE THREAD

**Issue by seanenroute** [Gizra/og#717] opened 2021-01-22 06:42 UTC
The UI is missing links for Add People, Invite People, Permissions, and Roles. Currently only "Members" is visible.

From other discussions it appears these functions are built into the newest version of Organic Groups but are only accessible by building custom modules. 

For us average developers who don't have a programming background nor the budget these are must have UI functions to be able to use this module.

**Comment by pfrenssen** [comment] 2021-07-14 16:16
Duplicate of #243

**Closed as completed by pfrenssen** 2021-07-14 16:16 UTC
