### ISSUE TITLE
MembershipManager::getMembership() is inefficient for users with many memberships

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/og#696] opened 2020-08-15 12:42 UTC
The current implementation of `MembershipManager::getMembership()` is a very simple affair which calls `::getMemberships()` to get the full array of memberships, then filters them down to the requested one.

This is slow and memory inefficient in case the user has a large number of memberships. Especially since it does a full load of all membership entities.

We should rework this to do a query, and statically cached the query result, similar to how it is handled in `::getMemberships()`.

**Comment by claudiu-cristea** [comment] 2020-08-17 10:40
This looks like a duplicate of #485. Isn't it?

**Comment by pfrenssen** [comment] 2020-08-17 16:37
No but it is related, #485 is about providing a persistent cache, this is about not loading more memberships than strictly required.

**Closed as completed** 2023-09-27 11:15 UTC
Labels: Drupal 8, Good first issue, Performance
